version: 0.2

phases:
  install: 
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-path: yes
  base-directory:  "dist"
  secondary-artifacts:
    ci_timer:
      files:
        - '**/*'
      discard-path: yes
      base-directory:  "dist"